// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.input_object_type.type

import com.apollographql.apollo.api.CustomScalarAdapters
import com.apollographql.apollo.api.Input
import com.apollographql.apollo.api.InputType
import com.apollographql.apollo.api.internal.ResponseAdapter
import com.example.input_object_type.type.adapter.ReviewRefInput_ResponseAdapter
import kotlin.Suppress

/**
 * Circle ref to review input
 */
@Suppress("NAME_SHADOWING", "UNUSED_ANONYMOUS_PARAMETER", "LocalVariableName",
    "RemoveExplicitTypeArguments", "NestedLambdaShadowedImplicitParameter", "PropertyName",
    "RemoveRedundantQualifierName")
data class ReviewRefInput(
  val reviewInput: Input<ReviewInput> = Input.absent()
) : InputType<ReviewRefInput> {
  override fun adapter(customScalarAdapters: CustomScalarAdapters):
      ResponseAdapter<ReviewRefInput> {
    val adapter = customScalarAdapters.getInputObjectAdapter("ReviewRefInput") {
      ReviewRefInput_ResponseAdapter(customScalarAdapters)
    }
    return adapter
  }
}
