// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.input_object_type.type.adapter

import com.apollographql.apollo.api.CustomScalarAdapters
import com.apollographql.apollo.api.Input
import com.apollographql.apollo.api.internal.InputResponseAdapter
import com.apollographql.apollo.api.internal.ResponseAdapter
import com.apollographql.apollo.api.internal.doubleResponseAdapter
import com.apollographql.apollo.api.internal.intResponseAdapter
import com.apollographql.apollo.api.internal.json.JsonReader
import com.apollographql.apollo.api.internal.json.JsonWriter
import com.example.input_object_type.type.ColorInput
import com.example.input_object_type.type.Episode
import com.example.input_object_type.type.Episode_ResponseAdapter
import com.example.input_object_type.type.ReviewRefInput
import java.lang.UnsupportedOperationException
import kotlin.Double
import kotlin.Int

class ColorInput_ResponseAdapter(
  customScalarAdapters: CustomScalarAdapters
) : ResponseAdapter<ColorInput> {
  val intAdapter: ResponseAdapter<Int> = intResponseAdapter

  val inputOfFloatAdapter: ResponseAdapter<Input<Double>> =
      InputResponseAdapter(doubleResponseAdapter)

  val floatAdapter: ResponseAdapter<Double> = doubleResponseAdapter

  val inputOfEpisodeAdapter: ResponseAdapter<Input<Episode>> =
      InputResponseAdapter(Episode_ResponseAdapter)

  val inputOfReviewRefInputAdapter: ResponseAdapter<Input<ReviewRefInput>> =
      InputResponseAdapter(ReviewRefInput_ResponseAdapter(customScalarAdapters))

  override fun fromResponse(reader: JsonReader): ColorInput = throw
      UnsupportedOperationException("InputObject used in output position")
  override fun toResponse(writer: JsonWriter, value: ColorInput) {
    writer.beginObject()
    writer.name("red")
    intAdapter.toResponse(writer, value.red)
    writer.name("green")
    inputOfFloatAdapter.toResponse(writer, value.green)
    writer.name("blue")
    floatAdapter.toResponse(writer, value.blue)
    writer.name("enumWithDefaultValue")
    inputOfEpisodeAdapter.toResponse(writer, value.enumWithDefaultValue)
    writer.name("reviewRefInput")
    inputOfReviewRefInputAdapter.toResponse(writer, value.reviewRefInput)
    writer.endObject()
  }
}
