// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.input_object_type.type.adapter

import com.apollographql.apollo.api.CustomScalarAdapters
import com.apollographql.apollo.api.Input
import com.apollographql.apollo.api.internal.InputResponseAdapter
import com.apollographql.apollo.api.internal.ResponseAdapter
import com.apollographql.apollo.api.internal.json.JsonReader
import com.apollographql.apollo.api.internal.json.JsonWriter
import com.example.input_object_type.type.ReviewInput
import com.example.input_object_type.type.ReviewRefInput
import java.lang.UnsupportedOperationException

class ReviewRefInput_ResponseAdapter(
  customScalarAdapters: CustomScalarAdapters
) : ResponseAdapter<ReviewRefInput> {
  val inputOfReviewInputAdapter: ResponseAdapter<Input<ReviewInput>> =
      InputResponseAdapter(ReviewInput_ResponseAdapter(customScalarAdapters))

  override fun fromResponse(reader: JsonReader): ReviewRefInput = throw
      UnsupportedOperationException("InputObject used in output position")
  override fun toResponse(writer: JsonWriter, value: ReviewRefInput) {
    writer.beginObject()
    writer.name("reviewInput")
    inputOfReviewInputAdapter.toResponse(writer, value.reviewInput)
    writer.endObject()
  }
}
