// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.example.input_object_type.type.adapter

import com.apollographql.apollo.api.CustomScalarAdapters
import com.apollographql.apollo.api.Input
import com.apollographql.apollo.api.internal.InputResponseAdapter
import com.apollographql.apollo.api.internal.ListResponseAdapter
import com.apollographql.apollo.api.internal.NullableResponseAdapter
import com.apollographql.apollo.api.internal.ResponseAdapter
import com.apollographql.apollo.api.internal.booleanResponseAdapter
import com.apollographql.apollo.api.internal.intResponseAdapter
import com.apollographql.apollo.api.internal.json.JsonReader
import com.apollographql.apollo.api.internal.json.JsonWriter
import com.apollographql.apollo.api.internal.stringResponseAdapter
import com.example.input_object_type.type.ColorInput
import com.example.input_object_type.type.CustomScalars
import com.example.input_object_type.type.Episode
import com.example.input_object_type.type.Episode_ResponseAdapter
import com.example.input_object_type.type.ReviewInput
import java.lang.UnsupportedOperationException
import java.util.Date
import kotlin.Boolean
import kotlin.Int
import kotlin.String
import kotlin.collections.List

class ReviewInput_ResponseAdapter(
  customScalarAdapters: CustomScalarAdapters
) : ResponseAdapter<ReviewInput> {
  val intAdapter: ResponseAdapter<Int> = intResponseAdapter

  val inputOfIntAdapter: ResponseAdapter<Input<Int>> = InputResponseAdapter(intResponseAdapter)

  val inputOfStringAdapter: ResponseAdapter<Input<String>> =
      InputResponseAdapter(stringResponseAdapter)

  val colorInputAdapter: ResponseAdapter<ColorInput> =
      ColorInput_ResponseAdapter(customScalarAdapters)

  val inputOfEpisodeAdapter: ResponseAdapter<Input<Episode>> =
      InputResponseAdapter(Episode_ResponseAdapter)

  val episodeAdapter: ResponseAdapter<Episode> = Episode_ResponseAdapter

  val inputOfListOfNullableDateAdapter: ResponseAdapter<Input<List<Date?>>> =
      InputResponseAdapter(ListResponseAdapter(NullableResponseAdapter(customScalarAdapters.responseAdapterFor<Date>(CustomScalars.Date))))

  val inputOfDateAdapter: ResponseAdapter<Input<Date>> =
      InputResponseAdapter(customScalarAdapters.responseAdapterFor<Date>(CustomScalars.Date))

  val inputOfListOfNullableEpisodeAdapter: ResponseAdapter<Input<List<Episode?>>> =
      InputResponseAdapter(ListResponseAdapter(NullableResponseAdapter(Episode_ResponseAdapter)))

  val inputOfListOfNullableIntAdapter: ResponseAdapter<Input<List<Int?>>> =
      InputResponseAdapter(ListResponseAdapter(NullableResponseAdapter(intResponseAdapter)))

  val inputOfListOfNullableStringAdapter: ResponseAdapter<Input<List<String?>>> =
      InputResponseAdapter(ListResponseAdapter(NullableResponseAdapter(stringResponseAdapter)))

  val listOfNullableStringAdapter: ResponseAdapter<List<String?>> =
      ListResponseAdapter(NullableResponseAdapter(stringResponseAdapter))

  val inputOfListOfNullableColorInputAdapter: ResponseAdapter<Input<List<ColorInput?>>> =
      InputResponseAdapter(ListResponseAdapter(NullableResponseAdapter(ColorInput_ResponseAdapter(customScalarAdapters))))

  val inputOfBooleanAdapter: ResponseAdapter<Input<Boolean>> =
      InputResponseAdapter(booleanResponseAdapter)

  val inputOfListOfListOfStringAdapter: ResponseAdapter<Input<List<List<String>>>> =
      InputResponseAdapter(ListResponseAdapter(ListResponseAdapter(stringResponseAdapter)))

  val inputOfListOfListOfEpisodeAdapter: ResponseAdapter<Input<List<List<Episode>>>> =
      InputResponseAdapter(ListResponseAdapter(ListResponseAdapter(Episode_ResponseAdapter)))

  val inputOfListOfListOfDateAdapter: ResponseAdapter<Input<List<List<Date>>>> =
      InputResponseAdapter(ListResponseAdapter(ListResponseAdapter(customScalarAdapters.responseAdapterFor<Date>(CustomScalars.Date))))

  val inputOfListOfListOfColorInputAdapter: ResponseAdapter<Input<List<List<ColorInput>>>> =
      InputResponseAdapter(ListResponseAdapter(ListResponseAdapter(ColorInput_ResponseAdapter(customScalarAdapters))))

  override fun fromResponse(reader: JsonReader): ReviewInput = throw
      UnsupportedOperationException("InputObject used in output position")
  override fun toResponse(writer: JsonWriter, value: ReviewInput) {
    writer.beginObject()
    writer.name("stars")
    intAdapter.toResponse(writer, value.stars)
    writer.name("nullableIntFieldWithDefaultValue")
    inputOfIntAdapter.toResponse(writer, value.nullableIntFieldWithDefaultValue)
    writer.name("commentary")
    inputOfStringAdapter.toResponse(writer, value.commentary)
    writer.name("favoriteColor")
    colorInputAdapter.toResponse(writer, value.favoriteColor)
    writer.name("enumWithDefaultValue")
    inputOfEpisodeAdapter.toResponse(writer, value.enumWithDefaultValue)
    writer.name("nonNullableEnumWithDefaultValue")
    episodeAdapter.toResponse(writer, value.nonNullableEnumWithDefaultValue)
    writer.name("nullableEnum")
    inputOfEpisodeAdapter.toResponse(writer, value.nullableEnum)
    writer.name("listOfCustomScalar")
    inputOfListOfNullableDateAdapter.toResponse(writer, value.listOfCustomScalar)
    writer.name("customScalar")
    inputOfDateAdapter.toResponse(writer, value.customScalar)
    writer.name("listOfEnums")
    inputOfListOfNullableEpisodeAdapter.toResponse(writer, value.listOfEnums)
    writer.name("listOfInt")
    inputOfListOfNullableIntAdapter.toResponse(writer, value.listOfInt)
    writer.name("listOfString")
    inputOfListOfNullableStringAdapter.toResponse(writer, value.listOfString)
    writer.name("listOfStringNonOptional")
    listOfNullableStringAdapter.toResponse(writer, value.listOfStringNonOptional)
    writer.name("listOfInputTypes")
    inputOfListOfNullableColorInputAdapter.toResponse(writer, value.listOfInputTypes)
    writer.name("booleanWithDefaultValue")
    inputOfBooleanAdapter.toResponse(writer, value.booleanWithDefaultValue)
    writer.name("booleanNonOptional")
    inputOfBooleanAdapter.toResponse(writer, value.booleanNonOptional)
    writer.name("listOfListOfString")
    inputOfListOfListOfStringAdapter.toResponse(writer, value.listOfListOfString)
    writer.name("listOfListOfEnum")
    inputOfListOfListOfEpisodeAdapter.toResponse(writer, value.listOfListOfEnum)
    writer.name("listOfListOfCustom")
    inputOfListOfListOfDateAdapter.toResponse(writer, value.listOfListOfCustom)
    writer.name("listOfListOfObject")
    inputOfListOfListOfColorInputAdapter.toResponse(writer, value.listOfListOfObject)
    writer.name("capitalizedField")
    inputOfStringAdapter.toResponse(writer, value.capitalizedField)
    writer.name("capitalizedInt")
    inputOfIntAdapter.toResponse(writer, value.capitalizedInt)
    writer.endObject()
  }
}
